### ISSUE TITLE
Unicode symbols are not displayed correctly

### ISSUE THREAD

**Issue by FeodorFitsner** [pglet/pglet#146]
![image](https://user-images.githubusercontent.com/5041459/171742478-e0e97498-51b7-42bc-bdf4-ef7437d05154.png)
![image](https://user-images.githubusercontent.com/5041459/171742513-52038bf6-2c59-48ab-a2f4-e89d80ad4cf6.png)

**Comment by ae5au** [comment]
@FeodorFitsner It looks like this problem was in PowerShell for you.  I've been using full emoji with PowerShell 7, but the same script doesn't render properly when executed with Windows PowerShell (5.1).  It might be possible to change settings and make it work in 5.1, but I haven't tried.

Anyway, disregard if this isn't related but thought I would share in case you haven't tried on 7.

**Comment by FeodorFitsner** [comment]
Thanks for sharing your observations!

Yeah, let's close this issue for now.
