### ISSUE TITLE
Upgrade: if pglet is running, update is failing

### ISSUE THREAD

**Issue by InesaFitsner** [pglet/pglet#41]

**Comment by c-nv-s** [comment]
Hey,
I wanted to mention that the pglet.sh script also does not stop installing if a more recent version number is present.
I tested this by installing v0.2.1 
Then I "sourced" the pglet.sh script which was already previously downloaded from v0.2.0 and I believe it proceeded to install the v0.2.0 binary over the v0.2.1 binary

**Comment by FeodorFitsner** [comment]
Right, it's currently pinned to an exact version. Funny enough, initially it was made with upgrade to a very recent version: https://github.com/pglet/pglet-bash/commit/3228c8afc3b1d65c74c98cebc8854b4013d9d04e#diff-f0f199502fb5ed2f0e93805edab564c05f574824d3006f4bad9f33018f63e8c9

I'm not sure which behavior is more expected?...

**Comment by FeodorFitsner** [comment]
Btw, I'm doing this in test scripts to always pull the latest:

```bash
# include Pglet helper
source <(curl -s https://pglet.io/pglet.sh)
```

**Comment by c-nv-s** [comment]
To be honest I don't think that the expected behavior should be for the script to potentially pull something new from the internet every time that it is sourced (for security reasons and for stability in production at least).

I think there should be some form of dedicated "pglet.sh --update" command which a user can run, separate to the normal functioning/purpose of the software.
This is then where the script checks the version number and advises if the software is outdated, up-to-date etc.

what are your thoughts?

**Comment by FeodorFitsner** [comment]
I've just realized that with Bash upgrade could look like running the same command again :)

```bash
curl -O https://pglet.io/pglet.sh
```
